# Generated by Django 5.0.6 on 2024-06-30 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_student_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
